//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Members')
export class MembersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  memberID: string;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  mobileNumber: string;

  @Column('text', { nullable: true })
  emailAddress: string;

  @Column('date', { nullable: true })
  joiningDate: Date;
}
