//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="JRS Earn" />
    <CardContent>
      This is an online earning app, you have to sign in by entering your mobile
      number and password, after that you have to login. In this app, you have
      to add at least 500 rupees. After adding 500 rupees, the user's account
      added to the app will be credited to his account daily. 50 rupees will be
      spent.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
